server:
  port: 8005
#mybatis
mybatis:
  #实体类配置
  type-aliases-package: com.etc.order.repository.entity
  #xml映射配置
  mapper-locations: classpath:mapper/*.xml
  configuration:
    #开启懒加载
    lazyLoadingEnabled: true
    #开启驼峰命名
    map-underscore-to-camel-case: true


#spring
spring:
  application:
    name: springcloud-order-app
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848


  redis:
    #redis数据库索引
    database: 0
    #redis服务器地址
    host: 127.0.0.1
    #redis端口号
    port: 6379
    #redis密码
    password:
    #redis连接池配置
    jedis:
      pool:
        #连接池最大的连接数（使用负值时表示没有任何限制）
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值时表示没有任何限制）
        max-wait: -1
        #连接池中最大空闲连接数
        max-idle: 10
        #连接池中最小空闲连接数
        min-idle: 0
        #连接超时（单位ms）
        timeout: 1000


#Eureka配置 服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
#      ,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: springclond-order-app-8005 #修改Eureka上默认描述信息！
#监控信息页面
info:
  app.name: etc-springcloud
  company.name: com.liuyuxiang







